# scons build file for rcapi
# author vhg

env = Environment()
env.Append(CPPPATH = ['.','$CODA/common/include'])
env.Append(CCFLAGS = ['-g','-O3'])
env.Append(LIBPATH = ['$CODA/Linux-x86_64/lib'])
env.Append(LIBS = ['libcmsg', 'libcmsgRegex', 'libcmsgxx', 'librt', 'libpthread', 'libdl'])
env.Object(source = 'rcapi.c' )
